### ISSUE TITLE
Autonomous

### ISSUE THREAD

**Issue by Henyahyah** [RedArrowRobotics/2024-21353-RobotCode#19]
I have an autonomous, but I need to test it on our practice field so adjust it to work. If we get that soon enough I'll try to make the more advanced version.

**Comment by Henyahyah** [comment]
its all working perfctly (exept the bucket being weak becaaue low batery) we just need to put in on a fiekd to adjust the fina 45* strafe elength

**Comment by CoderLiam926** [comment]
Will this ever be done?

**Comment by Henyahyah** [comment]
finished testing on the field and it is perfect now
